### ISSUE TITLE
Initial repository setup

### ISSUE THREAD

**Issue by szuperaz** [GetStream/stream-feeds-js#1]
## Architecture

The same monorepo structure we use for video. The only difference is that I'm going to create a `common` a package for functionalities that are shared among all of our products (user handling, WS connection etc.)

## Tasks

- [X] Create repository structure (I gave myself one day to see if I can do this with Nx, but couldn't really figure it out, so I copy-pasted the infrastructure from video)
- [X] Create release structure (Nx now has a release plugin which, in theory, has everything we need, so we can skip the [`jscutlery/semver` plugin](https://github.com/jscutlery/semver), I only tested this in dry run mode, but that was successful)
- [X] REST API layer using our in-house Go generator
- [X] WS connection (from `stream-chat-js`) 
- [X] State layer (from `stream-chat-js` thread manager)
- [x] Tweak TypeScript templates so they can work with multiple TS projects (for example Feeds doesn't need a `VideoAPI.ts` file, relative import paths will be different in each project, etc.) - ⏳ in progress
- [ ] CI setup (we should be mindful about this as CI for private repos costs us money, so most likely I'll turn this off at the beginning)
